baseURL: http://callingcharisma.netlify.app
languageCode: en-us
theme: graysx-hugo
title: Example Graysx Site
params:
  address: 123 Arch B1W, GNU/Linux
  email: callingcharisma@gmail.com
  facebook: '#'
  favicon: assets/favicon.png
  github: 
  logo: assets/img/logo.webp
  phone: '++4915730703057'
  sbtoken: TOKEN_HERE
  twitter: '#'
menu:
  main:
    - URL: '#about'
      name: About
      weight: 1
    - URL: '#projects'
      name: Projects
      weight: 2
    - URL: '#signup'
      name: Contact
      weight: 3
